import { createStyles } from "../../types/emotion-styles";

export const styles = createStyles({
  section: {
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    height: "calc(100vh - 55px)",
    padding: "0 25px 25px",
    boxSizing: "border-box",
    overflowY: "scroll",
    width: "calc(100vw - 200px)",
    "&::-webkit-scrollbar": {
      width: "3px",
    },
    "&::-webkit-scrollbar-track": {
      boxShadow: "inset 0 0 6px rgba(0, 0, 0, 0.3)",
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "darkgrey",
      outline: "1px solid slategrey",
    },
  },
  container: {
    width: "100%",
    maxWidth: "1950px",
    margin: "0 auto",
  },
  single_video_img: {
    width: "100%",
    margin: "0 0 15px",
  },
  single_video_time: {},
  single_video_title: {
    fontSize: "40px",
    fontWeight: 700,
    lineHeight: 1,
    margin: "0 0 15px 0",
  },
  single_video_channel: {
    fontSize: "20px",
    fontWeight: 400,
    lineHeight: 1,
    margin: "0 0 10px 0",
  },
  single_video_meta: {
    fontSize: "16px",
    lineHeight: 1,
    fontWeight: 400,
    margin: 0,
  },
  single_video_avatar: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-end",
    borderRadius: "50%",
    border: "1px solid blue",
    width: "50px",
    height: "50px",
    fontSize: "40px",
  },
  single_video_description: {
    margin: "15px 0 0",
    gap: "20px",
    display: "grid",
    gridTemplateColumns: "50px 1fr 100px",
    width: "100%",
  },
  single_video_text: {
    display: "flex",
    flexDirection: "column",
  },
  comment_wrapper: {
    backgroundColor: "#f0f0f0",
    boxSizing: "border-box",
    padding: "15px 25px",
    borderRadius: "5px",
    margin: "7px 0",
  },
  comment_text: {
    fontSize: "20px",
    lineHeight: 1,
    margin: "0 0 15px",
  },
  comment_date: {
    fontSize: "14px",
    lineHeight: 1,
    margin: "0 0 5px",
  },
  like_icon: {
    backgroundColor: "rgba(0, 0, 0, 0)",
    padding: 0,
    fill: "black",
    color: "white",
    width: "40px",
    height: "40px",
    outline: "none",
    border: "none",
    justifySelf: "flex-end",
    transform: "translate(0, -3px)",
    transition: "all .3s",
    "&.icon_active": {
      fill: "white",
    },
  },
  like_button: {
    cursor: "pointer",
    justifySelf: "end",
    backgroundColor: "white",
    boxSizing: "border-box",
    border: "1px solid grey",
    borderRadius: "5px",
    padding: "3px 7px",
    display: "grid",
    gridTemplateColumns: "40px 1fr",
    alignItems: "center",
    gap: "5px",
    transition: "all .3s",
    "&:hover": {
      backgroundColor: "#eee",
    },
    "&.like_active": {
      backgroundColor: "red",
      color: "white",
      border: "1px solid white",
    },
    "&.like_active:hover": {
      backgroundColor: "rgb(200, 0, 0)",
    },
  },
  like_counter: {
    fontSize: "18px",
    lineHeight: 1,
    fontWeight: 600,
    textAlign: "left",
    margin: "0 8px 0 0",
  },
  link: {
    color: "#1a73e8",
    fontWeight: 600,
    transition: "color .3s",
    "&:hover": {
      color: "#1557af",
    },
  },
});
