import { Video } from './models/video'
import { VideoCategory } from './models/videoCategories';

export const videos: Video[] = [
  {
  id: '1',
  image: './images/media.webp',
  duration: 2880,
  avatar: 'U',
  title: 'Название видео 1',
  channel: {name: 'Супер канал #1'},
  views: 0,
  createdAt: '2020-01-01',
  categories: [VideoCategory.Show, VideoCategory.Comedy],
  },
  {
  id: '2',
  image: './images/media.webp',
  duration: 924,
  avatar: 'V',
  title: 'Название видео 2',
  channel: {name: 'Супер канал #1'},
  views: 99,
  createdAt: '2021-01-01',
  categories: [VideoCategory.Show],
  },
  {
  id: '3',
  image: './images/media.webp',
  duration: 924,
  avatar: 'V',
  title: 'Название видео 3',
  channel: {name: 'Супер канал #1'},
  views: 1001,
  createdAt: '2021-03-28',
  categories: [VideoCategory.Comedy],
  },
  {
  id: '4',
  image: './images/media.webp',
  duration: 1084,
  avatar: 'V',
  title: 'Название видео 4',
  channel: {name: 'Супер канал #1'},
  views: 10001,
  createdAt: '2019-08-16',
  categories: [VideoCategory.Show],
  },
  {
  id: '5',
  image: './images/media.webp',
  duration: 687,
  avatar: 'V',
  title: 'Название видео 5',
  channel: {name: 'Супер канал #1'},
  views: 15000000,
  createdAt: '2020-04-05',
  categories: [VideoCategory.Comedy],
  },
  {
  id: '6',
  image: './images/media.webp',
  duration: 1354,
  avatar: 'V',
  title: 'Название видео 6',
  channel: {name: 'Супер канал #1'},
  views: 1,
  createdAt: '2021-10-04',
  categories: [VideoCategory.Show],
  },
];