import { Video } from './models/video'

export const videos: Video[] = [
  {
  id: 1,
  image: './images/media.webp',
  alt: 'media',
  time: '48:53',
  avatar: 'U',
  title: 'Название видео 1',
  channel: {name: 'Супер канал #1'},
  meta: {views: 0, date: '2020-01-01'},
  },
  {
  id: 2,
  image: './images/media.webp',
  alt: 'media',
  time: '15:24',
  avatar: 'V',
  title: 'Название видео 2',
  channel: {name: 'Супер канал #1'},
  meta: {views: 99, date: '2021-01-01'},
  },
  {
  id: 3,
  image: './images/media.webp',
  alt: 'media',
  time: '15:24',
  avatar: 'V',
  title: 'Название видео 3',
  channel: {name: 'Супер канал #1'},
  meta: {views: 1001, date: '2021-03-28'},
  },
  {
  id: 4,
  image: './images/media.webp',
  alt: 'media',
  time: '15:24',
  avatar: 'V',
  title: 'Название видео 4',
  channel: {name: 'Супер канал #1'},
  meta: {views: 10001, date: '2019-08-16'},
  },
  {
  id: 5,
  image: './images/media.webp',
  alt: 'media',
  time: '15:24',
  avatar: 'V',
  title: 'Название видео 5',
  channel: {name: 'Супер канал #1'},
  meta: {views: 15000000, date: '2020-04-05'},
  },
  {
  id: 6,
  image: './images/media.webp',
  alt: 'media',
  time: '15:24',
  avatar: 'V',
  title: 'Название видео 6',
  channel: {name: 'Супер канал #1'},
  meta: {views: 1, date: '2021-10-04'},
  },
];