import { Video } from './models/video'

export const videos: Video[] = [
  {
  id: 1,
  image: './images/media.webp',
  duration: 2880,
  avatar: 'U',
  title: 'Название видео 1',
  channel: {name: 'Супер канал #1'},
  views: 0,
  createdOn: '2020-01-01',
  },
  {
  id: 2,
  image: './images/media.webp',
  duration: 924,
  avatar: 'V',
  title: 'Название видео 2',
  channel: {name: 'Супер канал #1'},
  views: 99,
  createdOn: '2021-01-01',
  },
  {
  id: 3,
  image: './images/media.webp',
  duration: 924,
  avatar: 'V',
  title: 'Название видео 3',
  channel: {name: 'Супер канал #1'},
  views: 1001,
  createdOn: '2021-03-28',
  },
  {
  id: 4,
  image: './images/media.webp',
  duration: 1084,
  avatar: 'V',
  title: 'Название видео 4',
  channel: {name: 'Супер канал #1'},
  views: 10001,
  createdOn: '2019-08-16',
  },
  {
  id: 5,
  image: './images/media.webp',
  duration: 687,
  avatar: 'V',
  title: 'Название видео 5',
  channel: {name: 'Супер канал #1'},
  views: 15000000,
  createdOn: '2020-04-05',
  },
  {
  id: 6,
  image: './images/media.webp',
  duration: 1354,
  avatar: 'V',
  title: 'Название видео 6',
  channel: {name: 'Супер канал #1'},
  views: 1,
  createdOn: '2021-10-04',
  },
];